# Version themes: car brands
# * audi-1
# * bentley-2
# * chevrolet-3
# * dodge-4
# * elfin-5
# * ferrari-6

runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  secure: always
- url: .*
  script: main.app
  secure: always

libraries:
- name: flask
  version: 0.12
- name: pytz
  version: latest
- name: ssl
  version: latest

env_variables:
  PYTHONHTTPSVERIFY: 1
