# Version themes: car brands
# * audi-1
# * bentley-2
# * chevrolet-3
# * dodge-4
# * elfin-5

application: commute-pebble
version: elfin-5
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /headlights
  script: main.app
  secure: never
- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: latest
